# -*- coding: utf-8 -*-
"""
/***************************************************************************
 ShohanJump
                                 A QGIS plugin
 This plugin show specific Shohan (Areas of segmented forests in Japanese).
 Generated by Plugin Builder: http://g-sherman.github.io/Qgis-Plugin-Builder/
                              -------------------
        begin                : 2024-02-01
        version              : 20240507
        git sha              : $Format:%H$
        copyright            : (C) 2024 by Takeru Sanda
        email                : location.lab@sanda-takeru.com
 ***************************************************************************/
"""

from qgis.PyQt.QtCore import QSettings, QTranslator, QCoreApplication
from qgis.PyQt.QtGui import *
from qgis.PyQt.QtWidgets import QAction
from qgis.utils import iface
from qgis.core import QgsVectorLayer
from qgis.core import QgsProject, QgsMapLayer, QgsMapLayerProxyModel

from .resources import *
# Import the code for the dialog
from .shohan_jump_dialog import ShohanJumpDialog
import os.path

class ShohanJump:

    def __init__(self, iface):
        self.iface = iface
        self.plugin_dir = os.path.dirname(__file__)
        locale = QSettings().value('locale/userLocale')
        locale_path = os.path.join(
            self.plugin_dir,
            'i18n',
            'ShohanJump_{}.qm'.format(locale))

        if os.path.exists(locale_path):
            self.translator = QTranslator()
            self.translator.load(locale_path)
            QCoreApplication.installTranslator(self.translator)

        self.actions = []
        self.menu = self.tr(u'&Shohan Jump 2')
        self.toolbar = self.iface.addToolBar(u'ShohanJump2')
        self.toolbar.setObjectName(u'ShohanJump2')
        self.first_start = None

    def tr(self, message):
        return QCoreApplication.translate('ShohanJump2', message)


    def add_action(
        self,
        icon_path,
        text,
        callback,
        enabled_flag=True,
        add_to_menu=True,
        add_to_toolbar=True,
        status_tip=None,
        whats_this=None,
        parent=None):

        icon = QIcon(icon_path)
        action = QAction(icon, text, parent)
        action.triggered.connect(callback)
        action.setEnabled(enabled_flag)

        if status_tip is not None:
            action.setStatusTip(status_tip)

        if whats_this is not None:
            action.setWhatsThis(whats_this)

        if add_to_toolbar:
            self.toolbar.addAction(action)

        if add_to_menu:
            self.iface.addPluginToMenu(
                self.menu,
                action)

        self.actions.append(action)

        return action

    def initGui(self):
        # Pythonファイルのディレクトリを取得
        current_directory = os.path.dirname(os.path.abspath(__file__))

        # icon.pngのパスを作成
        icon_path = os.path.join(current_directory, "icon.png")
        #icon_path = ':/plugins/shohan_jump/icon.png'
        self.add_action(
            icon_path,
            text=self.tr(u'Shohan Jump 2'),
            callback=self.run,
            parent=self.iface.mainWindow())

        # will be set False in run()
        self.first_start = True

        self.dlg = ShohanJumpDialog()
     
    def unload(self):
        """Removes the plugin menu item and icon from QGIS GUI."""
        for action in self.actions:
            self.iface.removePluginMenu(
                self.tr(u'&Shohan Jump 2'),
                action)
            self.iface.removeToolBarIcon(action)

    def run(self):

        """全てのレイヤで選択解除する関数"""
        def deselect_all_features():
            layers = QgsProject.instance().mapLayers().values()
            for layer in layers:
                if layer.type() == QgsMapLayer.VectorLayer and layer.selectedFeatureCount() > 0:
                    layer.removeSelection()

        """条件に合う地物を選択する関数"""
        def select_features(layer, field_a, value_a, field_b, value_b, field_c):

            if value_b.strip() == '':  # 小班名が空白の場合
                layer.selectByExpression(f"{field_a} = {value_a}")
                
            else:  # 小班名が入力されている場合
                characters = len(value_b)
                i = 0
                while i < characters:
                    ShohanEdaban = 0
                    s = 0
                    if i + 2 < characters and value_b[i+1].isdigit() and value_b[i+2].isdigit():
                        ShohanEdaban = value_b[i+1:i+3]
                        s = 2
                    elif i + 1 < characters and value_b[i+1].isdigit():
                        ShohanEdaban = value_b[i+1]
                        s = 1
                    layer.selectByExpression(f"{field_a} = {value_a} and {field_b} LIKE '{value_b[i]}%' and {field_c} = {ShohanEdaban}", QgsVectorLayer.AddToSelection)
                    i += 1 + s
        
        """選択された小班にズームする関数"""
        def jump_the_shohan(layer):    
            canvas = iface.mapCanvas()
            canvas.zoomToSelected(layer)

        """実際の処理を行うメソッド"""
        # 小班区画にポリゴンレイヤのみ表示
        self.dlg.shohankukaku.setFilters(QgsMapLayerProxyModel.PolygonLayer)
        # 変数定議
        selected_features = 0
        comment = ''

        # 繰り返し処理、小班を検索して選択に加えていく。
        while selected_features == 0:
            self.dlg.show()
            result = self.dlg.exec_()
            if result:
                layer = self.dlg.shohankukaku.currentLayer()
                field_a = '林班主番'
                value_a = self.dlg.rinpan.value()
                field_b = '小班名'
                value_b = self.dlg.shohan.text()
                field_c = '小班枝番'

                # 全角文字を半角文字に変換する。
                translation_table = str.maketrans({chr(0xFF01 + i): chr(0x21 + i) for i in range(94)})
                value_b = value_b.translate(translation_table)

                # layerがベクタレイヤの場合、全部選択解除、小班検索。
                if layer is not None and layer.type() == QgsMapLayer.VectorLayer:
                    deselect_all_features()
                    select_features(layer, field_a, value_a, field_b, value_b, field_c)
                    selected_features = layer.selectedFeatureCount()

                # 小班にズームする。コメント更新。
                if selected_features:
                    jump_the_shohan(layer)
                    comment = ''
                else:
                    comment = '小班が存在しません。'
                self.dlg.label_5.setText(comment)
                self.dlg.label_5.setStyleSheet("QLabel { color : red; }")

            else:
                break
